version: "2"
checks:
    argument-count:
        config:
            threshold: 8
    file-lines:
        config:
            threshold: 500
    complex-logic:
        enabled: false
    method-complexity:
        enabled: false
exclude_patterns:
    - "docs/"
    - "tests/"
