language: python
python:
  - "2.7"

before_script: # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

before_install:
  - sudo apt-get install -qq python-numpy python-scipy python-matplotlib

install:
  - "pip install coverage"
  - "pip install coveralls"
  - "pip install pandas"
  - "pip install seaborn"

script:
  - "coverage run --source=opcsim setup.py test"
