name: build & release
on:
  release:
    types: [published]

jobs:
    build-n-publish:
        name: Build and publish to PyPI
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout branch
              uses: actions/checkout@v2

            - name: Setup python 
              uses: actions/setup-python@master
              with:
                python-version: 3.8
            
            - name: Install poetry
              uses: snok/install-poetry@v1
              with:
                virtualenvs-create: true
            
            - name: Install dependencies
              run: poetry install --no-interaction
            
            - name: Build and publish to PyPI
              run: |
                poetry build
                poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}

    # publish-to-docker:
    #     name: Build Docker image and push to DockerHub
    #     runs-on: ubuntu-20.04
    #     steps:
    #         - name: Checkout branch
    #           uses: actions/checkout@v2
            
    #         - name: Build and deploy Docker image
    #           uses: docker/build-push-action@v1
    #           with:
    #             username: ${{ secrets.DOCKER_USERNAME }}
    #             password: ${{ secrets.DOCKER_PASSWORD }}
    #             path: docker/
    #             repository: dhhagan/opcsim
    #             tags: latest
    #             tag_with_ref: true
    
  