name: Run unittests and push to coveralls
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]
    name: Python ${{ matrix.python }} tests
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      # - uses: actions/setup-python@master
      #   with:
      #     python-version: ${{ matrix.python }}
      
      # - name: Generate coverage report
      #   run: |
      #     pip install pytest
      #     pip install pytest-cov
      #     pytest --cov=./ --cov-report=xml
