name: Run unittests and push to coveralls
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]
    name: Python ${{ matrix.python }} tests
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python }}

      - name: Install poetry
        uses: dschep/install-poetry-action@v1.3
      
      - name: Install dependencies
        run: poetry install

      - name: Run tests and generate coverage report
        run: |
          poetry run pytest --cov=./ --cov-report=xml

      
      # - name: Generate coverage report
      #   run: |
      #     pip install pytest
      #     pip install pytest-cov
      #     pytest --cov=./ --cov-report=xml
